### ISSUE TITLE
Creating the Fully Fledged Android app

### ISSUE THREAD

**Issue by kinderasteroid** [kinderneutron/kinderneutron-web-app#13]

**Comment by kinderasteroid** [comment]
### Tasks To Perform 

- [ ]  Create Login Page
- [ ] Create SignUp Page
- [ ] Creating Landing Page With Notification

**Comment by kinderasteroid** [comment]
@varshavshetty May i Get the ETA for this work?
